name: Build LootModV2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Add BepInEx NuGet Source
      run: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n BepInEx

    - name: Build LootModV2
      run: |
        cd BepInExModsSource/LootModV2
        dotnet build -c Release

    - name: Upload DLL File
      uses: actions/upload-artifact@v4
      with:
        name: Dimraeth-LootModV2-DLL
        path: BepInExModsSource/LootModV2/bin/Release/**/*.dll
